# Generated by Django 3.1.4 on 2020-12-31 18:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Actor_name')),
                ('birth_year', models.PositiveIntegerField(default=0, verbose_name='Birth_year')),
                ('description', models.TextField(blank=True, verbose_name='Actor_description')),
                ('image', models.ImageField(upload_to='actors/', verbose_name='Actor_picture')),
            ],
            options={
                'verbose_name': 'Actor',
                'verbose_name_plural': 'Actors',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Category_name')),
                ('description', models.TextField(verbose_name='Category_Description')),
                ('url_film', models.SlugField(max_length=170, unique=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Genre_name')),
                ('description', models.TextField(verbose_name='Genre_description')),
                ('url', models.SlugField(max_length=170, unique=True)),
            ],
            options={
                'verbose_name': 'Genre',
                'verbose_name_plural': 'Genres',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Languages_name')),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Languages',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Title')),
                ('tagline', models.CharField(default='', max_length=150, verbose_name='Tag')),
                ('description', models.TextField(verbose_name='Description')),
                ('poster', models.ImageField(upload_to='movies/', verbose_name='Poster')),
                ('year', models.PositiveIntegerField(default=2020, verbose_name='Publishing year')),
                ('country', models.CharField(max_length=30, verbose_name='Country')),
                ('world_premiere', models.DateField(default=datetime.date.today, verbose_name='Premiere')),
                ('budget', models.PositiveIntegerField(default=0, help_text='Please enter movie_budget', verbose_name='Movie_budget')),
                ('url', models.SlugField(max_length=170, unique=True)),
                ('draft', models.BooleanField(default='False', verbose_name='Draft')),
                ('directed_by', models.CharField(blank=True, max_length=150, null=True, verbose_name='Directors')),
                ('produced_by', models.CharField(blank=True, max_length=200, null=True, verbose_name='Producers')),
                ('written_by', models.CharField(blank=True, max_length=200, null=True, verbose_name='Writers')),
                ('imdb_rtg', models.FloatField(default=0, verbose_name='IMDB_rating')),
                ('actors', models.ManyToManyField(related_name='Movie_actors', to='movies_app.Actor', verbose_name='Actors')),
                ('base_language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movies_app.language', verbose_name='Movie_base_language')),
                ('dubbing_language', models.ManyToManyField(related_name='into_languages', to='movies_app.Language', verbose_name='Movie_dubbing_language')),
                ('genres', models.ManyToManyField(to='movies_app.Genre', verbose_name='Genres')),
                ('movie_ctg', models.ManyToManyField(related_name='Into_category', to='movies_app.Category', verbose_name='Movie_category')),
                ('transcription_language', models.ManyToManyField(related_name='into_language', to='movies_app.Language', verbose_name='Movie_transcription_language')),
            ],
            options={
                'verbose_name': 'Movie',
                'verbose_name_plural': 'Movies',
            },
        ),
        migrations.CreateModel(
            name='RatingStar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveSmallIntegerField(default=0, verbose_name='Rating_value')),
            ],
            options={
                'verbose_name': 'Rating star',
                'verbose_name_plural': 'Rating stars',
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('text', models.TextField(max_length=5000, verbose_name='Review_text')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies_app.movie', verbose_name='Movie')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='movies_app.reviews', verbose_name='Parent')),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=15, verbose_name='IP adress')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies_app.movie', verbose_name='rating_movie')),
                ('star', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies_app.ratingstar', verbose_name='Rating')),
            ],
            options={
                'verbose_name': 'Rating',
                'verbose_name_plural': 'Ratings',
            },
        ),
        migrations.CreateModel(
            name='MovieShots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('image', models.ImageField(upload_to='movie_shots/', verbose_name='Picture')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies_app.movie', verbose_name='MovieShots')),
            ],
            options={
                'verbose_name': 'Movieshot',
                'verbose_name_plural': 'Movieshots',
            },
        ),
    ]
