# Generated by Django 3.1.4 on 2020-12-31 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_app', '0002_auto_20201231_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='world_premiere',
            field=models.DateField(default=2020, verbose_name='Premiere'),
        ),
    ]
