# Generated by Django 3.1.4 on 2021-01-01 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_app', '0003_auto_20201231_1955'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='url',
            new_name='url_slug',
        ),
        migrations.AlterField(
            model_name='movie',
            name='world_premiere',
            field=models.DateField(default=2021, verbose_name='Premiere'),
        ),
    ]
