# Generated by Django 3.1.4 on 2021-01-01 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies_app', '0004_auto_20210101_1143'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='url_slug',
            new_name='for_url',
        ),
    ]
