# Generated by Django 3.1.4 on 2021-01-01 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_app', '0006_auto_20210101_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieshots',
            name='image',
            field=models.ImageField(upload_to='movie_shots/', verbose_name='Picture'),
        ),
    ]
